name: mentalease_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animated_bottom_navigation_bar: ^1.0.0+2
  flashy_tab_bar2: ^0.0.10
  http: ^0.13.3
  shared_preferences: ^2.0.0
  intl: ^0.18.0
  fl_chart: ^0.69.0
  provider: ^6.1.2
  hive_flutter: ^1.1.0
  hive: ^2.0.0
  flutter_local_notifications: ^12.0.0
  share_plus: ^4.0.10
  carousel_slider:  ^4.0.0
  file_picker: ^8.1.2
  audioplayers: ^6.1.0
  timezone: ^0.9.4
  supabase_flutter: ^2.5.0
  supabase: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/mentalease_logo.png
    - assets/images/background.png
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/meditation_img.png
